### ISSUE TITLE
How to handle the missing dosages?

### ISSUE THREAD

**Issue by drveera** [hakyimlab/PrediXcan#25]
Hi Predixcan guys,
How to handle the missing dosages, while creating the predixcan format dosage files ? If its 'NA', the script throws error saying cannot convert string to float NA.
Thanks 
Veera

**Comment by hakyim** [comment]
Hi Veera

The best option is to impute the genotype and not have the NA. A very
simple though not optimal is to impute with the mean of the population.
HTH
Haky

**Comment by drveera** [comment]
Hi Haky,
Thanks for the quick response. I guess that's what the `convert_plink_to_dosage.py` does, right ? (I see that the script replaces `NA` with `MAF*2`. 

-Veera
