### ISSUE TITLE
PredictDB 1KG Data Availability

### ISSUE THREAD

**Issue by zgoodwin** [hakyimlab/PrediXcan#26]
Dear PrediXcan Team,

I am trying to access the GTEx V6p 1000 genomes prediction databases from PredictDB. Whenever I try to download any of the .db or text files, I get an XML page with an error that says "access denied". Do you know what could be preventing me from accessing this data? Thank you in advance for your time! I can provide additional details if necessary.

Best Regards,
Zane

**Comment by hakyim** [comment]
We are updating the 1000 Genomes based models using covariance values
computed in the training set. This will avoid many issues with SNPs not
used in the models.

Please bare with us while we upload the new models. We expect the update to
be done by the end of this week.

Haky

**Comment by zgoodwin** [comment]
Thanks for the rapid reply! I'll go ahead and close the issue.

-Zane
