### ISSUE TITLE
Full DB for missing genes

### ISSUE THREAD

**Issue by JYE-Lee** [hakyimlab/PrediXcan#28]
Hi, I found that the gene I am interested is missing from predictDB.
And I think that this gene was removed due to FDR correction as I saw one related question from FAQ.
Can I get the full prediction model without missing genes? Maybe the older version contain all genes.

Thank you!

**Comment by ScottPDickinson** [comment]
Hi there,
We can share the model with you, but to state the obvious, the prediction quality may not be very good.  What gene are you interested in? I can get back to you if that gene exists in the full models.

**Comment by JYE-Lee** [comment]
There are two genes I am interested in. But I am a bit concerned that this list is posted on your website. 
Thanks for your consideration.

-------- 원본 이메일 --------보낸 사람: Scott Dickinson <notifications@github.com> 날짜: 17/9/8  오전 12:49  (GMT+09:00) 받은 사람: hakyimlab/PrediXcan <PrediXcan@noreply.github.com> 참조: JYE-Lee <jylee521@gmail.com>, Author <author@noreply.github.com> 제목: Re: [hakyimlab/PrediXcan] Full DB for missing genes (#28) 
Hi there,

We can share the model with you, but to state the obvious, the prediction quality may not be very good.  What gene are you interested in? I can get back to you if that gene exists in the full models.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hakyimlab/PrediXcan","title":"hakyimlab/PrediXcan","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hakyimlab/PrediXcan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ScottPDickinson in #28: Hi there,\r\nWe can share the model with you, but to state the obvious, the prediction quality may not be very good.  What gene are you interested in? I can get back to you if that gene exists in the full models."}],"action":{"name":"View Issue","url":"https://github.com/hakyimlab/PrediXcan/issues/28#issuecomment-327841484"}}}

**Comment by JYE-Lee** [comment]
Dear Dr. Dickinson,

Hi,  just a reminder.
Have you checked the full model?

Thank you.
JYLee

**Comment by ScottPDickinson** [comment]
Hi JYLee,

Perhaps we should communicate over email directly? My email is spdickinson88 at gmail dot com.

Scott

**Comment by yunjuyang** [comment]
Hello. I also cannot find many genes of my interest from the prediction model. 
Is there way to include other genes (even though they present poor prediction quality) in the model?

**Comment by rbonazzola** [comment]
Hi Yunju,

I am sorry for the delay, apparently we missed this message. We can provide the full set of models (i.e. without filtering for prediction performance) if you still need them. You can contact me privately by sending an e-mail to rodbonazzola at gmail dot com.

Best,
Rodrigo
