### ISSUE TITLE
Gene_list Attribute Error

### ISSUE THREAD

**Issue by yunjuyang** [hakyimlab/PrediXcan#29]
I am trying to predict expression level using whole blood DB and got AttributeError. 
I have my files in the right place and no idea what is wrong with my code. 

Can anyone help me with this?

yjyang@HGCNT45:~/OFC/PrediXcan$ python PrediXcan.py --predict --dosages /home/yjyang/OFC/StudyData/GenotypeFiles/New_Impute/dosage --dosages_prefix cleft.chr --samples sample.txt --weights /home/yjyang/OFC/PrediXcan/GTEx-V6p-HapMap-2016-09-08/TW_Whole_Blood_0.5.db  --output_prefix /home/yjyang/OFC/PrediXcan/Output/WB
2018-01-16 13:07:21.964476 Preloading weights...
Traceback (most recent call last):
  File "PrediXcan.py", line 230, in <module>
    main()
  File "PrediXcan.py", line 212, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "PrediXcan.py", line 117, in save
    outfile.write('FID\t' + 'IID\t' + '\t'.join(self.gene_list) + '\n') # Nb. this lists the names of rows, not of columns
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'

**Comment by rbonazzola** [comment]
Hello Yunju,

It looks to me like PrediXcan could not read the dosage files. The current version of PrediXcan only supports **gzipped** dosage files as input, so if they are not compressed you need to gzip them with the `gzip dosage_file` command. There might also be a typo in the dosage prefix, but I guess you already double-checked this, so the former is more likely.

Let us know whether this was the case. If it wasn't I'll need to ask you more questions to help you solve this.

Thanks,
Rodrigo

**Comment by rbonazzola** [comment]
Hello again,

I forgot to mention that the names of the compressed dosage files must end with `.gz`.

Best,
Rodrigo

**Comment by hakyim** [comment]
Thank you, Rodrigo. Is this requirement clear from the readme/tutorial?

Thanks
Haky

**Comment by rbonazzola** [comment]
Actually it is not explicit in either. I will add it as soon as possible.

**Comment by yunjuyang** [comment]
Thank you so much! It works now.

**Comment by julandalf** [comment]
I have the same problem, I does't work for me...

**Comment by sandyren** [comment]
I also tried everything, seeming like same error kept showing up, the input file is named  as "chr2222.txt.gz, generated from  "convert_plink_to_dosage.py. The OS i am using is MAC. I am out of my wits now. Any help will be much appreciated!

./PrediXcan.py --predict --dosages /Volumes/LaCie/PrediXcan-master/data/dosages/ --dosages_prefix chr2222.txt --samples chr22.fam  --weights /Volumes/LaCie/PrediXcan-master/DGN-HapMap-2015/DGN-WB_0.5.db --output_prefix /Volumes/LaCie/PrediXcan-master/data/test
2019-02-15 13:28:21.839494 Preloading weights...
2019-02-15 13:28:23.131720 Processing chr2222.txt.gz
Traceback (most recent call last):
  File "./PrediXcan.py", line 230, in <module>
    main()
  File "./PrediXcan.py", line 212, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "./PrediXcan.py", line 117, in save
    outfile.write('FID\t' + 'IID\t' + '\t'.join(self.gene_list) + '\n') # Nb. this lists the names of rows, not of columns
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'
![image](https://user-images.githubusercontent.com/10345986/52836668-887e2f00-3126-11e9-962f-15535bd7589c.png)

**Comment by rbonazzola** [comment]
Hi sandyren,
The error means that PrediXcan is unable to predict the expression for any gene (the transcription matrix is empty), which can be due to several reasons. Given PrediXcan's succeeding in opening the genotype file ("`Processing chr2222.txt.gz`"), I think the problem could be related to the content of this file. The possibilities I can think of are: 
1) empty intersection between the SNPs in the prediction model and the genotype file (you can check the contents of the prediction model databases using software such as sqlitebrowser),
2) the genotype file uses a SNP identifier other than rsID's, and
3) the columns of the genotype file are not ordered properly.

Please let me know if your problem falls into in any of these cases, otherwise I will ask you to share a sample of your genotype file in order to further narrow the issue.

**Comment by sandyren** [comment]
Hey, thanks for the kind reply! Silly me, I forgot to convert the chr:pos to rsid earlier, now it works well! 

However, I have another two questions which might not be relevant here but I need your opinions regarding them:

(1) For multiple tissues, after association, I got multiple rows like this:
![image](https://user-images.githubusercontent.com/10345986/52927310-c1abde80-3374-11e9-90ac-6938bc6d1868.png)

I understand that the stand error is too small to calculate a P value, should I discard these results, or the fact that the standard error is small actually has some biological meanings.

(2) I noticed that for the .db data, all of them were generated using european populations. Does this affect the prediction using my raw data which is of the Chinese ancestry?

Any further clarification would be much appreciated!

Hongyan

**Comment by complexgenome** [comment]
It would be really kind if Readme/tutorial mentions that tool requires `.gz` input for dosage. It's frustrating otherwise, as users keep chasing the wind. Thanks.

**Comment by Heroico** [comment]
Hi Sariya,

I updated Software/Readme.md to make this clarification.

**Comment by Heroico** [comment]
@sandyren:
The models were trained on individuals of European Ancestry; thus they will not perform as well in Asian GWAS cohorts. Figure 2 in the MetaXcan paper shows the power loss:
https://www.nature.com/articles/s41467-018-03621-1/figures/2
