### ISSUE TITLE
what is the parameter setting when using elastic net using glmnet package

### ISSUE THREAD

**Issue by yuanzhongshang** [hakyimlab/PrediXcan#30]
Hi,
 Sorry for interrupting you. what is the parameter setting when using elastic net using glmnet package? just 
the default setting? For instance, what the lambda value when predicting the gene expression value in the Predxican?

Thanks a lot.

Bests,
Zhongshang

**Comment by hakyim** [comment]
Lambda is chosen to minimize cross validated mean square error. As
implemented in glmnet

Haky
