### ISSUE TITLE
dbSNP version 150 file for mapping SNPs

### ISSUE THREAD

**Issue by wangfan860** [hakyimlab/PrediXcan#35]
hello! I'm wondering where to get the dbSNP version 150 for mapping rsids? Thank you so much!

**Comment by Heroico** [comment]
Hi there:
You can use
`http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/snp150.txt.gz`
or 
`http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/snp150.txt.gz`
depending on whether you use hg38 or hg19
